# Generated by Django 4.1.1 on 2022-09-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.ForeignKey(db_column='institute', default='e3fcd046-c392-4f4a-8ac7-029c89fd9d4b', on_delete=django.db.models.deletion.DO_NOTHING, to='data.institutes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='role', default='b0a56a7e-314b-11ed-a96a-eb4f76a53aef', on_delete=django.db.models.deletion.DO_NOTHING, to='data.role'),
        ),
    ]
