# Generated by Django 4.1 on 2022-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, db_column='cityName', max_length=20, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('classroomnumber', models.CharField(blank=True, db_column='classroomNumber', max_length=10, null=True)),
                ('institute', models.UUIDField()),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(max_length=40)),
                ('telnumber', models.CharField(blank=True, db_column='telNumber', max_length=15, null=True)),
                ('institute', models.UUIDField()),
                ('user', models.CharField(max_length=20)),
                ('role', models.UUIDField()),
                ('sessionend', models.DateTimeField(blank=True, db_column='sessionEnd', null=True)),
                ('sessionstart', models.DateTimeField(blank=True, db_column='sessionStart', null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=40)),
                ('institutename', models.CharField(db_column='instituteName', max_length=40)),
                ('city', models.UUIDField()),
            ],
            options={
                'db_table': 'institutes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('permissionname', models.CharField(db_column='permissionName', max_length=20)),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('liquidkg', models.DecimalField(blank=True, db_column='liquidKg', decimal_places=65535, max_digits=65535, null=True)),
                ('solidkg', models.DecimalField(blank=True, db_column='solidKg', decimal_places=65535, max_digits=65535, null=True)),
                ('manager', models.UUIDField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('roletype', models.CharField(db_column='roleType', max_length=20)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.IntegerField(db_column='lastName')),
                ('institute', models.UUIDField()),
                ('clasroom', models.UUIDField()),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usclist',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('professor', models.UUIDField()),
                ('totaluscstudents', models.IntegerField(db_column='totalUscStudents')),
            ],
            options={
                'db_table': 'uscList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uscproduction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('manager', models.UUIDField(blank=True, null=True)),
                ('productiondate', models.DateTimeField(blank=True, db_column='productionDate', null=True)),
                ('menuprepare', models.TextField(db_column='menuPrepare')),
                ('totalusc', models.IntegerField(blank=True, db_column='totalUSC', null=True)),
            ],
            options={
                'db_table': 'uscProduction',
                'managed': False,
            },
        ),
    ]
